export const mockGuestList =  [
  {"name":"John Smith","gender":"Male","salutation":"Mr.","country":"USA","company":"MyCompany","title":"CEO","ranking":1,"isHostCompany":true},
  {"name":"Mary Johnson","gender":"Female","salutation":"Ms.","country":"UK","company":"CompanyA","title":"Software Engineer","ranking":9,"isHostCompany":false},
  {"name":"Robert Brown","gender":"Male","salutation":"Dr.","country":"Germany","company":"MyCompany","title":"CTO","ranking":3,"isHostCompany":true},
  {"name":"Linda Davis","gender":"Female","salutation":"Dr.","country":"France","company":"CompanyB","title":"Marketing Executive","ranking":8,"isHostCompany":false},
  {"name":"Michael Miller","gender":"Male","salutation":"Prof.","country":"Canada","company":"MyCompany","title":"Product Manager","ranking":5,"isHostCompany":true},
  {"name":"Elizabeth Wilson","gender":"Female","salutation":"Prof.","country":"Australia","company":"MyCompany","title":"CFO","ranking":3,"isHostCompany":true},
  {"name":"William Moore","gender":"Male","salutation":"Mr.","country":"Singapore","company":"CompanyC","title":"Designer","ranking":8,"isHostCompany":false},
  {"name":"Patricia Taylor","gender":"Female","salutation":"Ms.","country":"India","company":"MyCompany","title":"Software Engineer","ranking":10,"isHostCompany":true},
  {"name":"Charles Anderson","gender":"Male","salutation":"Dr.","country":"Japan","company":"CompanyD","title":"Sales Manager","ranking":7,"isHostCompany":false},
  {"name":"Susan Thomas","gender":"Female","salutation":"Prof.","country":"China","company":"MyCompany","title":"Product Manager","ranking":6,"isHostCompany":true},
  {"name":"David Jackson","gender":"Male","salutation":"Mr.","country":"UK","company":"MyCompany","title":"CEO","ranking":2,"isHostCompany":true},
  {"name":"Barbara White","gender":"Female","salutation":"Dr.","country":"USA","company":"CompanyA","title":"Marketing Executive","ranking":8,"isHostCompany":false},
  {"name":"Richard Harris","gender":"Male","salutation":"Prof.","country":"Germany","company":"MyCompany","title":"CFO","ranking":3,"isHostCompany":true},
  {"name":"Linda Martin","gender":"Female","salutation":"Ms.","country":"France","company":"MyCompany","title":"Designer","ranking":9,"isHostCompany":true},
  {"name":"Joseph Thompson","gender":"Male","salutation":"Mr.","country":"Canada","company":"CompanyB","title":"Software Engineer","ranking":10,"isHostCompany":false},
  {"name":"Jessica Garcia","gender":"Female","salutation":"Dr.","country":"Australia","company":"MyCompany","title":"Sales Manager","ranking":7,"isHostCompany":true},
  {"name":"Thomas Martinez","gender":"Male","salutation":"Prof.","country":"Singapore","company":"MyCompany","title":"Product Manager","ranking":5,"isHostCompany":true},
  {"name":"Sarah Robinson","gender":"Female","salutation":"Ms.","country":"India","company":"CompanyC","title":"Designer","ranking":9,"isHostCompany":false},
  {"name":"Daniel Clark","gender":"Male","salutation":"Dr.","country":"Japan","company":"MyCompany","title":"CTO","ranking":2,"isHostCompany":true},
  {"name":"Karen Rodriguez","gender":"Female","salutation":"Prof.","country":"China","company":"MyCompany","title":"CFO","ranking":3,"isHostCompany":true},
  {"name":"Matthew Lewis","gender":"Male","salutation":"Mr.","country":"UK","company":"CompanyD","title":"Software Engineer","ranking":10,"isHostCompany":false},
  {"name":"Nancy Lee","gender":"Female","salutation":"Ms.","country":"USA","company":"MyCompany","title":"Marketing Executive","ranking":8,"isHostCompany":true},
  {"name":"Anthony Walker","gender":"Male","salutation":"Dr.","country":"Germany","company":"MyCompany","title":"CEO","ranking":1,"isHostCompany":true},
  {"name":"Sandra Hall","gender":"Female","salutation":"Prof.","country":"France","company":"CompanyA","title":"Product Manager","ranking":6,"isHostCompany":false},
  {"name":"Steven Allen","gender":"Male","salutation":"Mr.","country":"Canada","company":"MyCompany","title":"Sales Manager","ranking":7,"isHostCompany":true},
  {"name":"Carol Young","gender":"Female","salutation":"Ms.","country":"Australia","company":"MyCompany","title":"Designer","ranking":9,"isHostCompany":true},
  {"name":"Kevin Hernandez","gender":"Male","salutation":"Dr.","country":"Singapore","company":"CompanyB","title":"Software Engineer","ranking":10,"isHostCompany":false},
  {"name":"Deborah King","gender":"Female","salutation":"Prof.","country":"India","company":"MyCompany","title":"CFO","ranking":3,"isHostCompany":true},
  {"name":"Brian Wright","gender":"Male","salutation":"Mr.","country":"Japan","company":"MyCompany","title":"CTO","ranking":2,"isHostCompany":true},
  {"name":"Sharon Lopez","gender":"Female","salutation":"Ms.","country":"China","company":"CompanyC","title":"Marketing Executive","ranking":8,"isHostCompany":false},
  {"name":"Edward Hill","gender":"Male","salutation":"Prof.","country":"UK","company":"MyCompany","title":"Product Manager","ranking":5,"isHostCompany":true},
  {"name":"Michelle Scott","gender":"Female","salutation":"Dr.","country":"USA","company":"MyCompany","title":"Sales Manager","ranking":7,"isHostCompany":true},
  {"name":"George Green","gender":"Male","salutation":"Mr.","country":"Germany","company":"CompanyD","title":"Designer","ranking":9,"isHostCompany":false},
  {"name":"Dorothy Adams","gender":"Female","salutation":"Prof.","country":"France","company":"MyCompany","title":"CEO","ranking":1,"isHostCompany":true},
  {"name":"Paul Baker","gender":"Male","salutation":"Dr.","country":"Canada","company":"MyCompany","title":"Software Engineer","ranking":10,"isHostCompany":true},
  {"name":"Laura Gonzalez","gender":"Female","salutation":"Ms.","country":"Australia","company":"CompanyA","title":"Product Manager","ranking":6,"isHostCompany":false},
  {"name":"Mark Nelson","gender":"Male","salutation":"Prof.","country":"Singapore","company":"MyCompany","title":"CTO","ranking":2,"isHostCompany":true},
  {"name":"Lisa Carter","gender":"Female","salutation":"Dr.","country":"India","company":"MyCompany","title":"CFO","ranking":3,"isHostCompany":true},
  {"name":"Donald Mitchell","gender":"Male","salutation":"Mr.","country":"Japan","company":"CompanyB","title":"Software Engineer","ranking":10,"isHostCompany":false},
  {"name":"Betty Perez","gender":"Female","salutation":"Ms.","country":"China","company":"MyCompany","title":"Marketing Executive","ranking":8,"isHostCompany":true},
  {"name":"Kenneth Roberts","gender":"Male","salutation":"Dr.","country":"UK","company":"MyCompany","title":"Product Manager","ranking":5,"isHostCompany":true},
  {"name":"Sandra Turner","gender":"Female","salutation":"Prof.","country":"USA","company":"CompanyC","title":"Designer","ranking":9,"isHostCompany":false},
  {"name":"Joshua Phillips","gender":"Male","salutation":"Mr.","country":"Germany","company":"MyCompany","title":"Sales Manager","ranking":7,"isHostCompany":true},
  {"name":"Ashley Campbell","gender":"Female","salutation":"Ms.","country":"France","company":"MyCompany","title":"Software Engineer","ranking":10,"isHostCompany":true},
  {"name":"Brian Parker","gender":"Male","salutation":"Prof.","country":"Canada","company":"CompanyD","title":"Marketing Executive","ranking":8,"isHostCompany":false},
  {"name":"Kimberly Evans","gender":"Female","salutation":"Dr.","country":"Australia","company":"MyCompany","title":"CFO","ranking":3,"isHostCompany":true},
  {"name":"Jason Edwards","gender":"Male","salutation":"Mr.","country":"Singapore","company":"MyCompany","title":"CEO","ranking":1,"isHostCompany":true},
  {"name":"Debra Collins","gender":"Female","salutation":"Ms.","country":"India","company":"CompanyA","title":"Product Manager","ranking":5,"isHostCompany":false},
  {"name":"Jeffrey Stewart","gender":"Male","salutation":"Dr.","country":"Japan","company":"MyCompany","title":"CTO","ranking":2,"isHostCompany":true},
  {"name":"Cynthia Sanchez","gender":"Female","salutation":"Prof.","country":"China","company":"MyCompany","title":"Designer","ranking":9,"isHostCompany":true},
  {"name":"Ryan Morris","gender":"Male","salutation":"Mr.","country":"UK","company":"CompanyB","title":"Sales Manager","ranking":7,"isHostCompany":false},
  {"name":"Rebecca Rogers","gender":"Female","salutation":"Ms.","country":"USA","company":"MyCompany","title":"Marketing Executive","ranking":8,"isHostCompany":true},
  {"name":"Jacob Reed","gender":"Male","salutation":"Prof.","country":"Germany","company":"MyCompany","title":"Software Engineer","ranking":10,"isHostCompany":true},
  {"name":"Catherine Cook","gender":"Female","salutation":"Dr.","country":"France","company":"CompanyC","title":"CFO","ranking":3,"isHostCompany":false},
  {"name":"Gary Morgan","gender":"Male","salutation":"Mr.","country":"Canada","company":"MyCompany","title":"Product Manager","ranking":5,"isHostCompany":true},
  {"name":"Pamela Bell","gender":"Female","salutation":"Prof.","country":"Australia","company":"MyCompany","title":"CEO","ranking":1,"isHostCompany":true},
  {"name":"Nicholas Murphy","gender":"Male","salutation":"Dr.","country":"Singapore","company":"CompanyD","title":"Software Engineer","ranking":10,"isHostCompany":false},
  {"name":"Amy Bailey","gender":"Female","salutation":"Ms.","country":"India","company":"MyCompany","title":"Designer","ranking":9,"isHostCompany":true},
  {"name":"Eric Rivera","gender":"Male","salutation":"Prof.","country":"Japan","company":"MyCompany","title":"CTO","ranking":2,"isHostCompany":true},
  {"name":"Angela Cooper","gender":"Female","salutation":"Dr.","country":"China","company":"CompanyA","title":"Marketing Executive","ranking":8,"isHostCompany":false},
  {"name":"Stephen Richardson","gender":"Male","salutation":"Mr.","country":"UK","company":"MyCompany","title":"CFO","ranking":3,"isHostCompany":true},
  {"name":"Shirley Cox","gender":"Female","salutation":"Ms.","country":"USA","company":"MyCompany","title":"Product Manager","ranking":5,"isHostCompany":true},
  {"name":"Larry Howard","gender":"Male","salutation":"Dr.","country":"Germany","company":"CompanyB","title":"CEO","ranking":1,"isHostCompany":false},
  {"name":"Dorothy Ward","gender":"Female","salutation":"Prof.","country":"France","company":"MyCompany","title":"Sales Manager","ranking":7,"isHostCompany":true},
  {"name":"Frank Torres","gender":"Male","salutation":"Mr.","country":"Canada","company":"MyCompany","title":"Designer","ranking":9,"isHostCompany":true},
  {"name":"Sandra Peterson","gender":"Female","salutation":"Dr.","country":"Australia","company":"CompanyC","title":"Software Engineer","ranking":10,"isHostCompany":false},
  {"name":"Scott Gray","gender":"Male","salutation":"Prof.","country":"Singapore","company":"MyCompany","title":"Product Manager","ranking":5,"isHostCompany":true},
  {"name":"Debra Ramirez","gender":"Female","salutation":"Ms.","country":"India","company":"MyCompany","title":"Marketing Executive","ranking":8,"isHostCompany":true},
  {"name":"Brandon James","gender":"Male","salutation":"Mr.","country":"Japan","company":"CompanyD","title":"CTO","ranking":2,"isHostCompany":false},
  {"name":"Rachel Watson","gender":"Female","salutation":"Prof.","country":"China","company":"MyCompany","title":"CEO","ranking":1,"isHostCompany":true},
  {"name":"Benjamin Brooks","gender":"Male","salutation":"Dr.","country":"UK","company":"MyCompany","title":"Software Engineer","ranking":10,"isHostCompany":true},
  {"name":"Catherine Kelly","gender":"Female","salutation":"Ms.","country":"USA","company":"CompanyA","title":"Designer","ranking":9,"isHostCompany":false},
  {"name":"Adam Sanders","gender":"Male","salutation":"Prof.","country":"Germany","company":"MyCompany","title":"Marketing Executive","ranking":8,"isHostCompany":true},
  {"name":"Janet Price","gender":"Female","salutation":"Dr.","country":"France","company":"MyCompany","title":"Product Manager","ranking":6,"isHostCompany":true},
  {"name":"Dennis Bennett","gender":"Male","salutation":"Mr.","country":"Canada","company":"CompanyB","title":"Sales Manager","ranking":7,"isHostCompany":false},
  {"name":"Pamela Wood","gender":"Female","salutation":"Prof.","country":"Australia","company":"MyCompany","title":"CTO","ranking":2,"isHostCompany":true},
  {"name":"Patrick Barnes","gender":"Male","salutation":"Dr.","country":"Singapore","company":"MyCompany","title":"CEO","ranking":1,"isHostCompany":true},
  {"name":"Rebecca Ross","gender":"Female","salutation":"Ms.","country":"India","company":"CompanyC","title":"Designer","ranking":9,"isHostCompany":false},
  {"name":"Alexander Henderson","gender":"Male","salutation":"Prof.","country":"Japan","company":"MyCompany","title":"CFO","ranking":3,"isHostCompany":true},
  {"name":"Katherine Coleman","gender":"Female","salutation":"Dr.","country":"China","company":"MyCompany","title":"Software Engineer","ranking":10,"isHostCompany":true},
  {"name":"Justin Jenkins","gender":"Male","salutation":"Mr.","country":"UK","company":"CompanyD","title":"Marketing Executive","ranking":8,"isHostCompany":false},
  {"name":"Stephanie Perry","gender":"Female","salutation":"Prof.","country":"USA","company":"MyCompany","title":"Sales Manager","ranking":7,"isHostCompany":true},
  {"name":"Aaron Powell","gender":"Male","salutation":"Dr.","country":"Germany","company":"MyCompany","title":"Product Manager","ranking":5,"isHostCompany":true},
  {"name":"Martha Long","gender":"Female","salutation":"Ms.","country":"France","company":"CompanyA","title":"CEO","ranking":1,"isHostCompany":false},
  {"name":"Sean Patterson","gender":"Male","salutation":"Prof.","country":"Canada","company":"MyCompany","title":"CTO","ranking":2,"isHostCompany":true},
  {"name":"Anna Hughes","gender":"Female","salutation":"Dr.","country":"Australia","company":"MyCompany","title":"Designer","ranking":9,"isHostCompany":true},
  {"name":"Brandon Flores","gender":"Male","salutation":"Mr.","country":"Singapore","company":"CompanyB","title":"Software Engineer","ranking":10,"isHostCompany":false},
  {"name":"Theresa Washington","gender":"Female","salutation":"Ms.","country":"India","company":"MyCompany","title":"Marketing Executive","ranking":8,"isHostCompany":true}
]
